<?php

/**
 * Implements hook_install().
 */
function jag_install() {
  drupal_set_message(t('You need to do some '.l('config', 'admin/config/user-interface/jag').' for jag module.'));
}

/**
 * Implements hook_uninstall().
 */
function jag_uninstall() {
  variable_del('jag_style_min');
  variable_del('jag_style_show');
  variable_del('jag_auto_play_start_label');
  variable_del('jag_auto_play_end_label');
  variable_del('jag_auto_play_speed');
}